---
title: "README"
author: "Cara Stainsby"
date: "2025-08-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# MSc Thesis Code Repository

This repository contains the code and data necessary to reproduce the analyses and figures for my MSc thesis:A Temporal Analysis of Relative Sea-Level Change in Ireland using Reconstruction data and IPCC AR6 Projections .

## Contents

- `data/` - All data files required for analyses. All 5 IPCC datasets, Ireland_data_2023.csv and         global_sl_recon_data.rds are required.
- `results/` - Output files including tables and figures (some large output files are excluded like the reslr output ireland_ni_gam_decomp.rds) 
-3 Rmd files: recon_projectionplots.Rmd,Linear_rate_analyses.Rmd, map.Rmd
- `README.md` - This file  

## Reproducibility

To reproduce the results:

1. Clone this repository  
2. Install necessary packages (`purrr`, `sf`, `reslr`, `rnaturalearth`, etc.)  
3. Run the scripts in order: 1. recon_projectionplots.Rmd, 2. Linear_rate_analyses.Rmd, 3. map.Rmd (not important really, just to make Fig. 1 in the written text)
4. Some model outputs are not included to reduce size but can be regenerated by running the scripts.

## Notes
- If you encounter any issues, please contact me at cara.stainsby.2021@mumail.ie

---

Thank you. 

